/**
 * Inlines the logo bitmaps used by `app/icon.tsx` and
 * `app/opengraph-image.tsx` as base64 data URIs in a generated TypeScript
 * module.
 *
 * Those two routes cannot read from `public/` at runtime: on Cloudflare
 * Workers the filesystem is not part of the deployed bundle, so a
 * `readFileSync` there throws `no such file or directory, readAll
 * '/bundle/public/...'` and takes the whole page render down with it.
 * Re-run with `pnpm logo-data` after changing either source image.
 */
import { writeFileSync } from "node:fs";
import { join } from "node:path";

import sharp from "sharp";

const ROOT = process.cwd();
const OUT = join(ROOT, "src", "lib", "logo-data.ts");

async function encode(file: string, height: number): Promise<string> {
  const buffer = await sharp(join(ROOT, "public", "images", file))
    .resize({ height, withoutEnlargement: true })
    .png({ compressionLevel: 9, palette: true })
    .toBuffer();
  return `data:image/png;base64,${buffer.toString("base64")}`;
}

async function main(): Promise<void> {
const glyph = await encode("logo-glyph.png", 220);
const markLight = await encode("logo-mark-light.png", 240);

writeFileSync(
  OUT,
  `// Generated by scripts/make-logo-data.ts — do not edit by hand.
// Run \`pnpm logo-data\` after changing the source images.
//
// These are inlined rather than read from \`public/\` because the icon and
// Open Graph routes render inside the Cloudflare Worker, where there is no
// filesystem to read from.

/** Arrowhead glyph only, no wordmark — legible down to 32px. */
export const LOGO_GLYPH_DATA_URI =
  "${glyph}";

/** Swoosh + "Aerotech", recoloured for dark backgrounds. */
export const LOGO_MARK_LIGHT_DATA_URI =
  "${markLight}";
`,
  "utf8",
);

  const size = (uri: string) => Math.round((uri.length * 3) / 4 / 1024);
console.log(`wrote src/lib/logo-data.ts — glyph ${size(glyph)} KB, mark ${size(markLight)} KB`);
}

void main();
